### ISSUE TITLE
Add treatment episode start and end dates as arguments to CMA_per_episode

### ISSUE THREAD

**Issue by Masswear** [ddediu/AdhereR#53]
As an alternative to calculating CMA_per_episode based on gap lenght, give option to provide episode start and end dates as arguments, e.g.:

```
CMA_per_episode(CMA="CMA1",
                data=med.events,
                maximum.permissible.gap = NULL,
                episode.start.date = "start_episode",  #Name of variable containing episode start date as string or date object
                episode.end.date = "end_episode"; #Name of variable containing episode end date as string or date object
                date.format="%m/%d/%Y")
```

**Comment by ddediu** [comment]
I guess that means that I have to call your code? If so, could you pls give me skeleton example that I can expand on?

**Comment by Masswear** [comment]
No, it means that the user should be able to override the internal calculation of episodes with `compute_internal_gaps` by providing episode start- and end dates per patient per medication class. Either as separate variable in the dataset or as separate dataset.

**Comment by ddediu** [comment]
I've been looking at this: currently, the episodes do not explicitly care about medication class (i.e., only a change in medication class *might* trigger a new episode), so what I propose is:

In `CMA_per_episode()` if you pass me an extra argument `treat.episodes` of type `data.frame` and structure: 

  - `patid` the patient ID
  - `episode.ID` the episode unique ID (increasing sequentially)
  - `episode.start` the episode start date
  - `end.episode.gap.days` the corresponding gap days of the last event in this episode
  - `episode.duration` the episode duration in days
  - `episode.end` the episode end date

(i.e., in the same format as `compute.treatment.episodes()` would have returned), I can use it internally instead of calling `compute.treatment.episodes()`.

Would this work for you?

**Comment by Masswear** [comment]
In principle yes, but the `data.frame` structure would ideally look like this:

- `patid` the patient ID
- `episode.ID` the episode unique ID (increasing sequentially)
- `medication.class` the medication class for which this episode is valid
- `episode.start` the episode start date
- `episode.end` the episode end date

This would reflect the situation in clinical practice, where medications are prescribed for specific durations, but durations don't need to be the same for each medication.

`end.episode.gap.days` is not known before CMA calculation and `episode.duration` is redundant when `episode.start` and `episode.end` are given.

**Comment by Masswear** [comment]
Users can now specify the parameter `treat.epi` for `CMA_per_episode`, in the form of a `data.frame`  containing the treatment episodes. It must contain the patient ID (as given in `ID.colname`), the episode unique ID (increasing sequentially, `episode.ID`), the episode start date (`episode.start`), the episode duration in days (`episode.duration`), and the episode end date (`episode.end`).

If `treat.epi` is specified, it overrides the default computation of treatment episodes by gap days. The `medication.class` column is not required because `CMA_per_episode` should only be used for single treatments. This option would make sense for a polypharmacy version of the function.
